### ISSUE TITLE
LOGO-TM.png不在https上

### ISSUE THREAD

**Issue by tomtiao** [xiexinhua2006/ShuangYe-Search#4]
这个问题发生在电脑版，手机版不存在这个问题。

**Comment by tomtiao** [comment]
auto.css中
`@media (max-width: 1335px) {
	body {
		margin: 0 10px;
		background-image: url();
	}
	.logo {
		background-image: url('http://m.shuangye.club/LOGO-TM.png');
	}`
应该是https？

**Comment by xiexinhua2006** [comment]
问题已经修复，感谢提交！
